### ISSUE TITLE
Struct Support 

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/zephyr#15]
**Feature**
The Zephyr language should support custom structs.

- [x] Scanner & parser struct definition support
- [x] Scanner & parser struct instantiation support
- [x] Typing
- [x] Automatic import of core.mem.malloc
- [x] Memory layout computation
- [x] MIR & Wasm generation

**Comment by CharlyCst** [comment]
**Scanner & Parser support**

We want to define structs definition as a new declaration:

```bnf
declaration    -> use | expose | function | imports | struct
sctruct        -> "pub"? "struct" IDENTIFIER struct_block ";"
struct_block   -> "{" struct_field* "}"
struct_field   ->  "pub"? IDENTIFIER ":" IDENTIFIER ";"
```

This introduce a new keyword: `struct`.

Then we need a way to instantiate structs, this is done as a new expression primary:

```bnf
primary        -> INTEGER | FLOAT | BOOLEAN | IDENTIFIER
                | IDENTIFIER "{" (field ( "," field )* ","?)? "}"
                | "false" | "true" | "(" expression ")"
field          -> IDENTIFIER ":" expression
```

**Comment by CharlyCst** [comment]
For the record, there was a subtlety: we can't use the grammar above because it creates an ambiguity in `if` and `while` expressions (because of the opening bracket that follow). Rust had to deal with the same issue (see [here](https://doc.rust-lang.org/reference/expressions/struct-expr.html)) and they simply disallowed struct literals inside `if`, `while` and the likes.
This mean that there is now 2 kind of `expression`, one that accept struct literals and one that does not.

**Comment by CharlyCst** [comment]
Fixed in  #91
