### ISSUE TITLE
Compiler Test Suite

### ISSUE THREAD

**Issue by Slyces** [CharlyCst/zephyr#18]
Support a test-suite for this compiler. The test suite will probably be written in `python3` for easier scripting abilities.

**Features**
- [ ] Extensive CLI
- [ ] No dependencies (python std)
- [x] Use colors
- [x] Support folder hierarchy
- [x] Compile test code
- [x] Run test code against supported runtimes
  - [x] wasmtime
- [ ] Continuous integration #16
- [ ] Filter tests by regex
- [ ] Support negative tests (expected to fail)
- [ ] Support selective re-testing (re-run on failed)
