### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Slyces** [CharlyCst/zephyr#25]
**Goal**
Achieve a complete continuous integration, testing every PR code, and eventually releasing binary versions of the compiler.

**Features**
- [x] Download the supported runtimes
  - [x] wasmtime
- [x] Compile the fork language on all supported platforms
  - [x] linux
- [ ] Cache downloads and artifacts
- [x] Run the test suite

**Issues**
Right now, the test-suite is expecting an existing runtime in the current shell. This means that the current implementation of the github workflow has to use a script to install the `wasmtime` runtime, then export its path to the shell before running the test-suite.

**Fallback Runtimes**
We might need a script to download runtimes. To facilitate the listing of supported/tested runtimes, one option would be to download a binary in a `runtimes/*` folder and use all of them in the test (when the appropriate feature/CLI will be implemented in #18).

For later use, we might need more complicated scripting to download the runtimes in the version of the system we are supporting. Where should that script go? Under the test-suite, as these runtimes will/may be used by the test-suite? Should we provide a specific CLI to use downloaded runtimes as a fallback if they are not installed?

Note: @CharlyCst mentions a NodeJs runtime in #16 that would not need any download/fallback step. It might be a cleaner option before supporting multiple runtimes.
