### ISSUE TITLE
Runtime Package

### ISSUE THREAD

**Issue by CharlyCst** [CharlyCst/zephyr#86]
This issue tracks the progress of the development of runtime packages for Zephyr.

- [x]  Support `runtime` packages (#87)
- [x] Allow function import from the host
- [ ] Define expected imports
- [ ] Support runtime interfaces
